Query to find primary keys with serial types
mfvanek/pg-index-health-sql pull request #46
Opened 2024-06-02 14:25 UTC by mfaulther

Relates to https://github.com/mfvanek/pg-index-health/issues/317

2024-06-02 18:35 UTC, mfvanek commented
@mfaulther 
Looks good!
Could you update readme.md as well?

2024-06-02 18:36 UTC, mfvanek requested changes
Please update readme.md as well

2024-06-03 19:31 UTC, mfaulther commented
> @mfaulther Looks good! Could you update readme.md as well?

Done

2024-06-04 06:44 UTC, mfvanek approved these changes

2024-06-04 06:45 UTC, merged